server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # this should handle routing errors by ensuring
    # the browser can always find the index.html
    error_page 404 /index.html;

    location /api/ {
        # the trailing slash here is crucial
        # it maps http://localhost/api/users -> http://backend:8080/users
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    include /etc/nginx/mime.types;
}
