# This properties file will be used when the backend is running in a docker.
# It will use PostgreSQL to meet stretch goals.

# Overrides for PostgreSQL (Docker)
spring.datasource.url=jdbc:postgresql://db:5432/training_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate can handle DDL for Postgres easily
spring.jpa.hibernate.ddl-auto=update